ADDRESS = "127.0.0.1"
SERVER_PORT = 5600
SERVER_ID = 1111

MESSAGE_END_SESSION = "END_SESSION"
MESSAGE_START_TRAINING = "START_TRAINING"
MESSAGE_FL_UPDATE = "FL_UPDATE"
MESSAGE_GET_ALL_NODES = "GET_ALL_NODES"
MESSAGE_ALL_NODES = "ALL_NODES"
MESSAGE_MODEL_SHARE = "MODEL_SHARE"
MESSAGE_SHARING_COMPLETE = "SHARING_COMPLETE"
MESSAGE_START_ASSEMBLY = "START_ASSEMBLY"

THRESHOLD = 0.25
PRIME = 65537.0
BUFFER = 50

FIELD_SIZE = 10 ** 3
Q = 10 ** 10
CHUNK_SIZE = 400
BIT_SIZE = 4096
NODES = 50
ROUNDS = 10
EPOCHS = 2
DATASET = ['cifar-10', 'f-mnist', 'mnist', 'svhn']
